### ISSUE TITLE
asyncio causes teardowns to mark as failures

### ISSUE THREAD

**Issue by nnboskovic** [wwarne/fastapi_sqlalchemy_v2_alembic#1]
Getting this error trying to run tests; the tests themselves pass in pytest but the overall run is marked as failed since the teardown is marked as failed due to this.

RuntimeError: Task <Task pending name='Task-46' coro=<_wrap_asyncgen_fixture.<locals>._asyncgen_fixture_wrapper.<locals>.finalizer.<locals>.async_finalizer() running at /home/[...]/.venv/lib/python3.10/site-packages/pytest_asyncio/plugin.py:334> cb=[_run_until_complete_cb() at /usr/lib/python3.10/asyncio/base_events.py:184]> got Future <Future pending cb=[Protocol._on_waiter_completed()]> attached to a different loop

ERROR [sqlalchemy.pool.impl.AsyncAdaptedQueuePool] Exception closing connection <AdaptedConnection <asyncpg.connection.Connection object at 0x7c74aa4b6890>>

**Comment by wwarne** [comment]
Hello. Could you be able to provide some example of a failing test or your project?

**Comment by nnboskovic** [comment]
> Hello. Could you be able to provide some example of a failing test or your project?

The tests themselves work fine; the issue is the teardown. I'm afraid I can't provide the project itself, but I have a feeling the problem might be that the FastAPI app in the test starts a database client, and the test themselves start another. I could be wrong though. Let me know if there is anything in particular I can provide, because I handle the database how you do

**Comment by wwarne** [comment]
@nnboskovic 
I was thinking about this problem and remembered that I had some problems with `pytest_asyncio` package when I was using fastapi. 

Fastapi itself uses `anyio` under the hood. And `pytest_asyncio` has its own `eventloop` fixture which were causing troubles for me because pytest_asyncio created eventloop and anyio created another eventloop.

I see your error message comes from `pytest_asyncio`. So i suggest to try and remove this package.
After that you probably need to find and remove @pytest.mark.asyncio from your tests 

if you have the same autouse fixture for anyio as I have in this repo:
```
@pytest.fixture(scope="session", autouse=True)
def anyio_backend():
    return "asyncio", {"use_uvloop": True}
```
than anything should be working (or you can use @pytest.mark.anyio to mark).

**Comment by nnboskovic** [comment]
That did it! Thanks a bunch!!

**Comment by nnboskovic** [comment]
Although now I get this running a second test:

```
File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

ERROR [api.routers.auth] User registration error: Task <Task pending name='starlette.middleware.base.BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.coro' coro=<BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.coro() running at /home/[...]/.venv/lib/python3.10/site-packages/starlette/middleware/base.py:151> cb=[TaskGroup._spawn.<locals>.task_done() at /home/[...]/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py:699]> got Future <Future pending cb=[Protocol._on_waiter_completed()]> attached to a different loop
```

**Comment by nnboskovic** [comment]
nm, solved
